root: /Users/user010/Desktop/Programming/ML/STS

datasets:
  stsb_train:
    hf_params:
      path: stsb_multi_mt
      name: en
      split: train

  stsb_val:
    hf_params:
      path: stsb_multi_mt
      name: en
      split: test


models:
  mini_lm:
    st_params:
      model_name_or_path: 'paraphrase-MiniLM-L6-v2'
  
  pp_roberta:
    st_params:
      model_name_or_path: "sentence-transformers/paraphrase-distilroberta-base-v1"


configs:
  models_comparison: '${root}/configs/models_comparison.yaml'
  fine_tune: '${root}/configs/fine_tune.yaml'

